---


'.review':
  script:
    - 'export TOXENV="${CI_JOB_NAME##review}"'
    - 'python3 -m pip install tox'
    - 'python3 -m tox'
    - 'python3 -m tox -e package'

'review py35':
  extends: '.review'
  image: 'python:3.6'

'review py36':
  extends: '.review'
  image: 'python:3.6'

'review py37':
  extends: '.review'
  image: 'python:3.7'

'review py38':
  extends: '.review'
  image: 'python:3.8'

'review py39':
  extends: '.review'
  image: 'python:3.9-rc'


...  # EOF
